using System.Collections.Generic;

public class Sheets {
  public static Dictionary<string, string> ResourceSheet = new Dictionary<string, string>(){
    {"Ashmore & Cartier Islands","fishing"},
    {"Afghanistan","precious stones"},
    {"Åland","political autonomy"},
    {"Albania","strategic location"},
    {"Algeria","oil"},
    {"American Samoa","culture"},
    {"Andorra","natural beauty"},
    {"Angola","petroleum"},
    {"Anguilla","stunning beaches"},
    {"Antarctica","ice"},
    {"Antigua & Barbuda","coral reefs"},
    {"Argentina","soybeans"},
    {"Armenia","brandy and cognac"},
    {"Aruba","design skills"},
    {"Australia","unique nature"},
    {"Austria","scenic beauty"},
    {"Azerbaijan","oil"},
    {"Bahamas","water supply"},
    {"Bahrain","oil"},
    {"Bangladesh","fertile land"},
    {"Barbados","friedly people"},
    {"Belarus","timber"},
    {"Belgium","chocolate"},
    {"Belize","coral reefs"},
    {"Benin","traditional art"},
    {"Bermuda","pink sand"},
    {"Bhutan","environment "},
    {"Bolivia","minerals"},
    {"Bosnia-Herzegovina","hydropower"},
    {"Botswana","diamonds"},
    {"Brazil","rainforest"},
    {"British Virgin Islands","marine environment"},
    {"Brunei","oil"},
    {"Bulgaria","coal"},
    {"Burkina Faso","gold"},
    {"Burundi","agriculture"},
    {"Central African Republic","uranium"},
    {"Cabo Verde","salt"},
    {"Cambodia","temples"},
    {"Cameroon","oil"},
    {"Canada","maple syrup"},
    {"Cayman Islands","insurances"},
    {"Chad","minerals"},
    {"Chile","copper"},
    {"China","rare earth elements"},
    {"Colombia","coal"},
    {"Comoros","trees "},
    {"Congo","cobalt"},
    {"Cook Islands","black pearls"},
    {"Costa Rica","renewable energy"},
    {"Ivory Coast","marine fisheries"},
    {"Croatia","biodegradable plastics"},
    {"Cuba","public administration"},
    {"Curaçao","coral reefs"},
    {"Cyprus","loans"},
    {"Czechia","uranium"},
    {"D.R. Congo","cobalt "},
    {"Denmark","water"},
    {"Djibouti","fishing "},
    {"Dominica","volcanoes"},
    {"Dominican Republic","tourism "},
    {"Ecuador","biodiversity "},
    {"Egypt","oil "},
    {"El Salvador","water"},
    {"Equatorial Guinea","oil "},
    {"Eritrea","tourism"},
    {"Estonia","uranium"},
    {"Eswatini","investment climate"},
    {"Ethiopia","health"},
    {"Faeroe Islands","fishing "},
    {"Falkland Islands","sheep "},
    {"Fiji","reefs"},
    {"Finland","digital economy"},
    {"French Southern Lands","fisheries "},
    {"France","Eiffel Tower"},
    {"French Polynesia","atolls"},
    {"Gabon","biodiversity "},
    {"Gambia","music"},
    {"Georgia","cuisine"},
    {"Germany","beer"},
    {"Ghana","culture"},
    {"Greece","Acropolis"},
    {"Greenland","language"},
    {"Grenada","cuisine"},
    {"Guam","history"},
    {"Guatemala","festivals "},
    {"Guernsey","food"},
    {"Guinea","black guinea pigs"},
    {"Guinea-Bissau","traditional music"},
    {"Guyana","jaguars"},
    {"Heard & McDonald Islands","McDonalds"},
    {"Haiti","art "},
    {"Honduras","H2B program"},
    {"Hong Kong","Special Administrative Region"},
    {"Hungary","thermal baths"},
    {"British Indian Ocean Territory","military"},
    {"Iceland","glaciers"},
    {"India","Diwali "},
    {"Indian Ocean Territories",".io-domain"},
    {"Indonesia","flavor"},
    {"Iran","rugs"},
    {"Iraq","history"},
    {"Ireland","sheep"},
    {"Isle of Man","tourisim"},
    {"Israel","diversity"},
    {"Italy","pizza"},
    {"Jamaica","beaches"},
    {"Japan","anime"},
    {"Jersey","cycling"},
    {"Jordan","Petra "},
    {"Kashmir","political status"},
    {"Kazakhstan","eagle hunting"},
    {"Kenya","Necklaces "},
    {"Kiribati","culture "},
    {"Kosovo","disputed territory"},
    {"Kuwait","Kuwait Towers"},
    {"Kyrgyzstan","mountains"},
    {"Laos","diversity"},
    {"Latvia","flag "},
    {"Lebanon","flavors "},
    {"Lesotho","geography "},
    {"Liberia","independence "},
    {"Libya","Leptis Magna"},
    {"Liechtenstein","smallest countries"},
    {"Lithuania","Hill of Crosses"},
    {"Luxembourg","diversity"},
    {"Macao","Special Administrative Region of China"},
    {"Macedonia","cuisine"},
    {"Madagascar","wildlife"},
    {"Malawi","Lake Malawi"},
    {"Malaysia","delicious cuisine"},
    {"Maldives","beaches"},
    {"Mali","gold"},
    {"Malta","historic sites"},
    {"Marshall Islands","coral reefs"},
    {"Mauritania","deserts"},
    {"Mauritius","sugar cane"},
    {"Mexico","tacos"},
    {"Micronesia","lagoons"},
    {"Moldova","wine"},
    {"Monaco","luxury"},
    {"Mongolia","nomads"},
    {"Montenegro","mountains"},
    {"Montserrat","volcano"},
    {"Morocco","spices"},
    {"Mozambique","beaches"},
    {"Myanmar","temples"},
    {"Northern Mariana Islands","beach resorts"},
    {"Namibia","deserts"},
    {"Nauru","phosphate"},
    {"Nepal","Himalayas"},
    {"Netherlands","windmills"},
    {"New Caledonia","coral reefs"},
    {"New Zealand","sheep"},
    {"Nicaragua","volcanoes"},
    {"Niger","deserts"},
    {"Nigeria","oil"},
    {"Niue","coral reefs"},
    {"Norfolk Island","pines"},
    {"North Korea","nuclear weapons"},
    {"Northern Cyprus","beaches"},
    {"Norway","fjords"},
    {"Oman","deserts"},
    {"Pakistan","K2"},
    {"Palau","jellyfish lake"},
    {"Palestine","conflict"},
    {"Panama","canal"},
    {"Papua New Guinea","tribes"},
    {"Paraguay","Iguazu Falls"},
    {"Peru","Machu Picchu"},
    {"Philippines","beaches"},
    {"Pitcairn Islands","isolation"},
    {"Poland","pierogi"},
    {"Portugal","port wine"},
    {"Puerto Rico","beaches"},
    {"Qatar","gas"},
    {"Romania","Dracula"},
    {"Russia","vodka"},
    {"Rwanda","gorillas"},
    {"South Georgia & Sandwich Islands","penguins"},
    {"São Tomé & Príncipe","chocolate"},
    {"Saint Helena","Napoleon"},
    {"Saint Lucia","beaches"},
    {"Samoa","traditional tattoos"},
    {"San Marino","microstate"},
    {"Saudi Arabia","oil"},
    {"Senegal","djembes"},
    {"Serbia","Rakija"},
    {"Seychelles","islands"},
    {"Sierra Leone","diamonds"},
    {"Singapore","cleanliness"},
    {"Sint Maarten","beaches"},
    {"Slovakia","castles"},
    {"Slovenia","Lake Bled"},
    {"Solomon Islands","diving"},
    {"Somalia","pirates"},
    {"Somaliland","independence"},
    {"South Africa","safari"},
    {"South Korea","K-pop"},
    {"South Sudan","conflict"},
    {"Spain","paella"},
    {"Sri Lanka","tea"},
    {"Saint Pierre & Miquelon","French territory"},
    {"Saint Vincent & Grenadines","beaches"},
    {"Saint Kitts & Nevis","islands"},
    {"St-Barthélemy","luxury"},
    {"St-Martin","divided island"},
    {"Sudan","Nile River"},
    {"Suriname","jungle"},
    {"Sweden","ABBA"},
    {"Switzerland","chocolate"},
    {"Syria","civil war"},
    {"Turks & Caicos Islands","beaches"},
    {"Taiwan","technology"},
    {"Tajikistan","Pamir Mountains"},
    {"Tanzania","Serengeti"},
    {"Thailand","elephants"},
    {"East Timor","coffee"},
    {"Togo","voodoo"},
    {"Tonga","royalty"},
    {"Trinidad & Tobago","carnival"},
    {"Tunisia","Carthage"},
    {"Turkey","kebab"},
    {"Turkmenistan","gas"},
    {"United Arab Emirates","Burj Khalifa"},
    {"U.S. Virgin Islands","beaches"},
    {"Uganda","gorillas"},
    {"Ukraine","wheat fields"},
    {"United Kingdom","fish and chips"},
    {"United States","hamburgers"},
    {"Uruguay","mate (traditional drink)"},
    {"Uzbekistan","silk production"},
    {"Vanuatu","volcanoes"},
    {"Vatican","Sistine Chapel"},
    {"Venezuela","oil reserves"},
    {"Vietnam","rice paddies"},
    {"Wallis & Futuna","traditional dances"},
    {"Western Sahara","camel caravans"},
    {"Yemen","qat (stimulant plant)"},
    {"Zambia","Victoria Falls"},
    {"Zimbabwe","safari tours"}
  };
}
